name: Build Java Library

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Angular dependencies
        run: |
          cd front
          npm install --legacy-peer-deps

      - name: Build Angular
        run: |
          cd front
          npm run build --prod
      
      - name: Copy Angular dist to Spring static folder
        run: |
          mkdir -p back/src/main/resources/static
          cp -r front/dist/* back/src/main/resources/static/

      - name: Configurar JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Resolve Spring Dependecies
        run: |
          cd back
          mvn clean dependency:copy-dependencies -s settings.xml
        env:
          PACKAGER_TOKEN: ${{ secrets.PACKAGER_TOKEN }}
      
      - name: Build Spring Test
        run: |
          cd back
          mvn verify -s settings.xml
        env:
          PACKAGER_TOKEN: ${{ secrets.PACKAGER_TOKEN }}
      
      
      
      - name: Construir o projeto
        if: success()
        run: |
          cd back
          mvn package -DskipTests --file pom.xml -s settings.xml
        env:
          PACKAGER_TOKEN: ${{ secrets.PACKAGER_TOKEN }}

      - name: Disponibilizar o JAR como artefato
        uses: actions/upload-artifact@v4
        with:
          name: nostra-massa
          path: target/*.jar